# Generated by Django 2.1.7 on 2019-02-27 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_answer', models.BooleanField(default=False)),
                ('correct', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttemptExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField()),
                ('my_score', models.FloatField()),
                ('original_exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Exam')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=True)),
                ('attempt_exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taken.AttemptExam')),
                ('original_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Question')),
            ],
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='attempt_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taken.AttemptQuestion'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='original_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Answer'),
        ),
    ]
