# Generated by Django 2.1.7 on 2019-02-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptanswer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
