# Generated by Django 2.1.7 on 2019-03-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='premium_member',
            field=models.BooleanField(default=True),
        ),
    ]
