# Generated by Django 2.1.7 on 2019-02-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='answer',
            name='links',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='reasons',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
