# Generated by Django 2.1.7 on 2019-02-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190227_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='links',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='reasons',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
