# Generated by Django 2.1.7 on 2019-02-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20190227_0433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name_plural': 'Subject Topics'},
        ),
    ]
