# Generated by Django 2.1.7 on 2019-03-06 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20190227_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Subject Topics'},
        ),
    ]
