# Generated by Django 2.1.7 on 2019-03-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20190306_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='premium_content',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='premium_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topics',
            name='premium_content',
            field=models.BooleanField(default=True),
        ),
    ]
