# Generated by Django 2.1.7 on 2019-03-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20190306_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField(default=None)),
                ('premium_content', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Topics')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Topic Lessons',
            },
        ),
    ]
