# Generated by Django 2.1.7 on 2019-04-05 06:29

import content.models.subject
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_subject_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='logo',
            field=models.ImageField(null=True, upload_to=content.models.subject.get_logo_path),
        ),
        migrations.AlterField(
            model_name='subject',
            name='banner',
            field=models.ImageField(null=True, upload_to=content.models.subject.get_banner_path),
        ),
    ]
