# Generated by Django 2.1.7 on 2019-04-09 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20190409_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='logo',
        ),
    ]
