# Generated by Django 2.1.7 on 2019-04-09 02:30

import content.models.course
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_course_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.ImageField(null=True, upload_to=content.models.course.get_logo_path),
        ),
    ]
