# Generated by Django 2.1.7 on 2019-04-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_course_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['pk'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Topic Lessons'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['pk'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Subject Topics'},
        ),
    ]
