# Generated by Django 2.1.7 on 2019-04-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20190415_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='arrangement',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='arrangement',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='arrangement',
            field=models.IntegerField(null=True),
        ),
    ]
