# Generated by Django 2.1.7 on 2019-05-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20190428_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['pk', 'arrangement']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['pk', 'arrangement'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Topic Lessons'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['pk', 'arrangement']},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['pk', 'arrangement'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Subject Topics'},
        ),
        migrations.AddField(
            model_name='exam',
            name='arrangement',
            field=models.IntegerField(null=True),
        ),
    ]
