# Generated by Django 2.1.7 on 2019-05-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20190503_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['arrangement']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['pk', 'arrangement'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Topic Lessons'},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['pk', 'arrangement'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Subject Topics'},
        ),
        migrations.AddField(
            model_name='course',
            name='arrangement',
            field=models.IntegerField(null=True),
        ),
    ]
