# Generated by Django 2.1.7 on 2019-06-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20190605_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='assessment_limit',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='assessment_limit',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
